name: 'Hello World Arruda'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
    descriptio: 'Who to Greet'
    required: true
    default: World
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
